// Code-block language labels, shared by the blog preview header and the editor's language picker.
export const LANG_DISPLAY: Record<string, string> = {
  js: 'JavaScript',
  javascript: 'JavaScript',
  ts: 'TypeScript',
  typescript: 'TypeScript',
  py: 'Python',
  python: 'Python',
  java: 'Java',
  cpp: 'C++',
  c: 'C',
  go: 'Go',
  rust: 'Rust',
  sql: 'SQL',
  bash: 'Bash',
  sh: 'Shell',
  json: 'JSON',
  html: 'HTML',
  css: 'CSS',
  yaml: 'YAML',
  xml: 'XML',
  kotlin: 'Kotlin',
  swift: 'Swift',
  cs: 'C#',
  php: 'PHP',
  ruby: 'Ruby',
  scala: 'Scala',
  r: 'R',
};
