/**
 * Bulk-submits a JSON array of MCQ questions (e.g. generated by the prompt in
 * docs/content_prompt_nimcet_mcqs.md) to the question bulk-create admin API. Standalone —
 * reads only from the file you point it at and the env vars below, no other project code
 * involved, safe to run repeatedly for future content batches without needing this repo's
 * assistant in the loop again.
 *
 * The API caps a single request at 100 questions, so this script chunks the input file
 * into batches automatically — you don't need to pre-split it.
 *
 * Usage:
 *   SEED_API_KEY=xxx API_BASE_URL=https://syllabuzai.com npx tsx scripts/submit-questions.ts questions.json
 *   npx tsx scripts/submit-questions.ts questions.json --dry-run   (validates shape, submits nothing)
 *
 * API_BASE_URL defaults to http://localhost:3000 (dev). Point it at your production origin
 * and use the production SEED_API_KEY (from .env.production) to publish live.
 */
import { readFile } from 'fs/promises';

interface QuestionOption {
  key: string;
  text: string;
  isCorrect: boolean;
}

interface QuestionPayload {
  stem: string;
  options: QuestionOption[];
  explanation?: string;
  difficulty?: 'EASY' | 'MEDIUM' | 'HARD' | 'EXPERT';
  tags?: string[];
  nodeIds?: string[];
  examIds: string[];
  status?: 'DRAFT' | 'IN_REVIEW' | 'PUBLISHED' | 'ARCHIVED';
}

const BATCH_SIZE = 100;

function chunk<T>(items: T[], size: number): T[][] {
  const chunks: T[][] = [];
  for (let i = 0; i < items.length; i += size) chunks.push(items.slice(i, i + size));
  return chunks;
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const filePath = args.find((a) => !a.startsWith('--'));
  if (!filePath) {
    console.error('Usage: npx tsx scripts/submit-questions.ts <questions.json> [--dry-run]');
    process.exit(1);
  }

  const apiKey = process.env.SEED_API_KEY;
  const baseUrl = process.env.API_BASE_URL ?? 'http://localhost:3000';
  if (!dryRun && !apiKey) {
    console.error('SEED_API_KEY env var is required (unless --dry-run)');
    process.exit(1);
  }

  const raw = await readFile(filePath, 'utf8');
  const questions: QuestionPayload[] = JSON.parse(raw);
  if (!Array.isArray(questions)) {
    console.error('Expected the JSON file to contain an array of question objects');
    process.exit(1);
  }

  const batches = chunk(questions, BATCH_SIZE);
  console.log(`Loaded ${questions.length} question(s) from ${filePath} -> ${baseUrl}, in ${batches.length} batch(es) of up to ${BATCH_SIZE}`);
  if (dryRun) console.log('--dry-run: validating shape only, nothing will be submitted\n');

  let ok = 0;
  let failed = 0;

  for (const [batchIndex, batch] of batches.entries()) {
    const batchLabel = `batch ${batchIndex + 1}/${batches.length}`;

    let batchValid = true;
    for (const [i, q] of batch.entries()) {
      const label = `${batchLabel} #${i + 1}`;
      if (!q.stem || !Array.isArray(q.options) || q.options.length < 2 || !Array.isArray(q.examIds) || q.examIds.length === 0) {
        console.error(`✗ [${label}] missing required field (stem/options/examIds) — skipped`);
        failed++;
        batchValid = false;
        continue;
      }
      const correctCount = q.options.filter((o) => o.isCorrect).length;
      if (correctCount !== 1) {
        console.error(`✗ [${label}] "${q.stem.slice(0, 50)}…" must have exactly one correct option, found ${correctCount}`);
        failed++;
        batchValid = false;
      }
    }
    if (!batchValid) {
      console.error(`✗ [${batchLabel}] skipped entire batch — fix the item(s) above and re-run\n`);
      continue;
    }

    if (dryRun) {
      console.log(`  would submit ${batchLabel}: ${batch.length} question(s), e.g. "${batch[0].stem.slice(0, 60)}…"`);
      continue;
    }

    try {
      const res = await fetch(`${baseUrl}/api/v1/admin/questions/bulk-create`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey! },
        body: JSON.stringify(batch),
      });
      const json = await res.json();
      if (!res.ok) {
        console.error(`✗ [${batchLabel}] ${res.status}: ${json.error ?? 'unknown error'} — whole batch rejected, nothing in it was created`);
        failed += batch.length;
      } else {
        for (const created of json.data) {
          console.log(`✓ [${batchLabel}] created id=${created.id} "${String(created.stem).slice(0, 50)}…"`);
        }
        ok += json.data.length;
      }
    } catch (err) {
      console.error(`✗ [${batchLabel}] request failed: ${err instanceof Error ? err.message : err} — whole batch rejected`);
      failed += batch.length;
    }
  }

  console.log(`\nDone: ${ok} created, ${failed} failed${dryRun ? ' (dry run)' : ''}.`);
  if (failed > 0) process.exit(1);
}

main();
