/**
 * Bulk-submits a JSON array of articles (e.g. generated by an LLM prompt) to the blog
 * admin API. Standalone — reads only from the file you point it at and the env vars
 * below, no other project code involved, safe to run repeatedly for future content
 * batches without needing this repo's assistant in the loop again.
 *
 * Usage:
 *   SEED_API_KEY=xxx API_BASE_URL=https://scholar247.org npx tsx scripts/submit-articles.ts articles.json
 *   npx tsx scripts/submit-articles.ts articles.json --dry-run   (validates shape, submits nothing)
 *
 * API_BASE_URL defaults to http://localhost:3000 (dev). Point it at your production
 * origin and use the production SEED_API_KEY (from .env.production) to publish live.
 */
import { readFile } from 'fs/promises';

interface ArticlePayload {
  title: string;
  slug?: string;
  summary?: string;
  body: string;
  status?: 'DRAFT' | 'IN_REVIEW' | 'PUBLISHED' | 'ARCHIVED';
  visibility?: 'PUBLIC' | 'PRIVATE' | 'AUDIENCE_RESTRICTED';
}

async function main() {
  const args = process.argv.slice(2);
  const dryRun = args.includes('--dry-run');
  const filePath = args.find((a) => !a.startsWith('--'));
  if (!filePath) {
    console.error('Usage: npx tsx scripts/submit-articles.ts <articles.json> [--dry-run]');
    process.exit(1);
  }

  const apiKey = process.env.SEED_API_KEY;
  const baseUrl = process.env.API_BASE_URL ?? 'http://localhost:3000';
  if (!dryRun && !apiKey) {
    console.error('SEED_API_KEY env var is required (unless --dry-run)');
    process.exit(1);
  }

  const raw = await readFile(filePath, 'utf8');
  const articles: ArticlePayload[] = JSON.parse(raw);
  if (!Array.isArray(articles)) {
    console.error('Expected the JSON file to contain an array of article objects');
    process.exit(1);
  }

  console.log(`Loaded ${articles.length} article(s) from ${filePath} -> ${baseUrl}`);
  if (dryRun) console.log('--dry-run: validating shape only, nothing will be submitted\n');

  let ok = 0;
  let failed = 0;

  for (const [i, article] of articles.entries()) {
    const label = article.title ?? `#${i + 1}`;
    if (!article.title || !article.body) {
      console.error(`✗ [${label}] missing required field (title/body) — skipped`);
      failed++;
      continue;
    }

    if (dryRun) {
      console.log(`  would submit: "${article.title}" (slug: ${article.slug ?? '<auto>'}, status: ${article.status ?? 'DRAFT'})`);
      continue;
    }

    try {
      const res = await fetch(`${baseUrl}/api/v1/admin/blog`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', 'x-api-key': apiKey! },
        body: JSON.stringify(article),
      });
      const json = await res.json();
      if (!res.ok) {
        console.error(`✗ [${label}] ${res.status}: ${json.error ?? 'unknown error'}`);
        failed++;
      } else {
        console.log(`✓ [${label}] created id=${json.data.id} slug=${json.data.slug}`);
        ok++;
      }
    } catch (err) {
      console.error(`✗ [${label}] request failed: ${err instanceof Error ? err.message : err}`);
      failed++;
    }
  }

  console.log(`\nDone: ${ok} created, ${failed} failed${dryRun ? ' (dry run)' : ''}.`);
  if (failed > 0) process.exit(1);
}

main();
